import type { StudentRow } from "../_types/students.types";

export const STUDENT_ROWS: StudentRow[] = [
  {
    initials: "AC",
    classroom: "Teoria musical",
    classroomFilter: "teoria-musical",
    classroomVariant: "blue",
    email: "ana.costa@email.com",
    module: "Módulo I",
    moduleFilter: "module-i",
    moduleVariant: "violet",
    name: "Ana Clara Costa",
    phone: "(11) 98765-1111",
    status: "Ativo",
    statusFilter: "active",
  },
  {
    initials: "BH",
    classroom: "Violino",
    classroomFilter: "violino",
    classroomFilters: ["teoria-musical", "solfejo", "violino"],
    classroomVariant: "pink",
    email: "bruno.silva@email.com",
    module: "Módulo II",
    moduleFilter: "module-ii",
    moduleVariant: "orange",
    name: "Bruno Henrique Silva",
    phone: "(11) 98765-2222",
    status: "Inativo",
    statusFilter: "inactive",
  },
  {
    initials: "CR",
    classroom: "Trompete",
    classroomFilter: "trompete",
    classroomFilters: ["teoria-musical", "solfejo", "trompete"],
    classroomVariant: "blue",
    email: "camila.rocha@email.com",
    module: "Módulo III",
    moduleFilter: "module-iii",
    moduleVariant: "orange",
    name: "Camila Rocha",
    phone: "(11) 98765-3333",
    status: "Trancamento",
    statusFilter: "locked",
  },
  {
    initials: "DP",
    classroom: "Teclado",
    classroomFilter: "teclado",
    classroomFilters: ["teoria-musical", "solfejo", "teclado"],
    classroomVariant: "pink",
    email: "diego.pires@email.com",
    module: "Módulo II",
    moduleFilter: "module-ii",
    moduleVariant: "orange",
    name: "Diego Pires",
    phone: "(11) 98765-4444",
    status: "Ativo",
    statusFilter: "active",
  },
  {
    initials: "ES",
    classroom: "Contrabaixo",
    classroomFilter: "contrabaixo",
    classroomVariant: "blue",
    email: "ester.sousa@email.com",
    module: "Módulo I",
    moduleFilter: "module-i",
    moduleVariant: "violet",
    name: "Ester Sousa",
    phone: "(11) 98765-5555",
    status: "Ativo",
    statusFilter: "active",
  },
  {
    initials: "FM",
    classroom: "Classe 1",
    classroomFilter: "classe-1",
    classroomVariant: "pink",
    email: "felipe.martins@email.com",
    module: "Módulo I",
    moduleFilter: "module-i",
    moduleVariant: "violet",
    name: "Felipe Martins",
    phone: "(11) 98765-6666",
    status: "Ativo",
    statusFilter: "active",
  },
  {
    initials: "GL",
    classroom: "Classe 2",
    classroomFilter: "classe-2",
    classroomVariant: "blue",
    email: "giovana.lima@email.com",
    module: "Módulo I",
    moduleFilter: "module-i",
    moduleVariant: "violet",
    name: "Giovana Lima",
    phone: "(11) 98765-7777",
    status: "Inativo",
    statusFilter: "inactive",
  },
  {
    initials: "HS",
    classroom: "Saxofone",
    classroomFilter: "saxofone",
    classroomFilters: ["teoria-musical", "solfejo", "saxofone"],
    classroomVariant: "pink",
    email: "henrique.santos@email.com",
    module: "Módulo II",
    moduleFilter: "module-ii",
    moduleVariant: "orange",
    name: "Henrique Santos",
    phone: "(11) 98765-8888",
    status: "Ativo",
    statusFilter: "active",
  },
  {
    initials: "IM",
    classroom: "Flauta",
    classroomFilter: "flauta",
    classroomFilters: ["teoria-musical", "solfejo", "flauta"],
    classroomVariant: "blue",
    email: "isabela.melo@email.com",
    module: "Módulo II",
    moduleFilter: "module-ii",
    moduleVariant: "orange",
    name: "Isabela Melo",
    phone: "(11) 98765-9999",
    status: "Trancamento",
    statusFilter: "locked",
  },
  {
    initials: "JP",
    classroom: "Canto coral",
    classroomFilter: "canto-coral",
    classroomFilters: ["teoria-musical", "solfejo", "canto-coral"],
    classroomVariant: "pink",
    email: "joao.pedro@email.com",
    module: "Módulo III",
    moduleFilter: "module-iii",
    moduleVariant: "orange",
    name: "João Pedro",
    phone: "(11) 97654-1111",
    status: "Ativo",
    statusFilter: "active",
  },
  {
    initials: "KS",
    classroom: "Clarinete",
    classroomFilter: "clarinete",
    classroomFilters: ["teoria-musical", "solfejo", "clarinete"],
    classroomVariant: "blue",
    email: "karina.silveira@email.com",
    module: "Módulo III",
    moduleFilter: "module-iii",
    moduleVariant: "orange",
    name: "Karina Silveira",
    phone: "(11) 97654-2222",
    status: "Inativo",
    statusFilter: "inactive",
  },
  {
    initials: "LR",
    classroom: "Violoncelo",
    classroomFilter: "violoncelo",
    classroomFilters: ["teoria-musical", "solfejo", "violoncelo"],
    classroomVariant: "pink",
    email: "lucas.ribeiro@email.com",
    module: "Módulo II",
    moduleFilter: "module-ii",
    moduleVariant: "orange",
    name: "Lucas Ribeiro",
    phone: "(11) 97654-3333",
    status: "Ativo",
    statusFilter: "active",
  },
  {
    initials: "MT",
    classroom: "Guitarra",
    classroomFilter: "guitarra",
    classroomFilters: ["teoria-musical", "solfejo", "guitarra"],
    classroomVariant: "blue",
    email: "mariana.teixeira@email.com",
    module: "Módulo III",
    moduleFilter: "module-iii",
    moduleVariant: "orange",
    name: "Mariana Teixeira",
    phone: "(11) 97654-4444",
    status: "Trancamento",
    statusFilter: "locked",
  },
  {
    initials: "NC",
    classroom: "Solfejo",
    classroomFilter: "solfejo",
    classroomFilters: ["teoria-musical", "solfejo"],
    classroomVariant: "blue",
    email: "natalia.castro@email.com",
    module: "Módulo II",
    moduleFilter: "module-ii",
    moduleVariant: "orange",
    name: "Natália Castro",
    phone: "(11) 97654-5555",
    status: "Ativo",
    statusFilter: "active",
  },
  {
    initials: "OP",
    classroom: "Teoria musical",
    classroomFilter: "teoria-musical",
    classroomFilters: ["teoria-musical", "solfejo"],
    classroomVariant: "pink",
    email: "otavio.pereira@email.com",
    module: "Módulo III",
    moduleFilter: "module-iii",
    moduleVariant: "orange",
    name: "Otávio Pereira",
    phone: "(11) 97654-6666",
    status: "Inativo",
    statusFilter: "inactive",
  },
  {
    initials: "PA",
    classroom: "Flauta",
    classroomFilter: "flauta",
    classroomFilters: ["teoria-musical", "solfejo", "flauta"],
    classroomVariant: "blue",
    email: "priscila.alves@email.com",
    module: "Módulo II",
    moduleFilter: "module-ii",
    moduleVariant: "orange",
    name: "Priscila Alves",
    phone: "(11) 97654-7777",
    status: "Ativo",
    statusFilter: "active",
  },
  {
    initials: "QR",
    classroom: "Classe 1",
    classroomFilter: "classe-1",
    classroomVariant: "pink",
    email: "quentin.rocha@email.com",
    module: "Módulo I",
    moduleFilter: "module-i",
    moduleVariant: "violet",
    name: "Quentin Rocha",
    phone: "(11) 97654-8888",
    status: "Trancamento",
    statusFilter: "locked",
  },
  {
    initials: "RS",
    classroom: "Canto coral",
    classroomFilter: "canto-coral",
    classroomFilters: ["teoria-musical", "solfejo", "canto-coral"],
    classroomVariant: "blue",
    email: "renata.souza@email.com",
    module: "Módulo III",
    moduleFilter: "module-iii",
    moduleVariant: "orange",
    name: "Renata Souza",
    phone: "(11) 97654-9999",
    status: "Ativo",
    statusFilter: "active",
  },
  {
    initials: "TG",
    classroom: "Violino",
    classroomFilter: "violino",
    classroomFilters: ["teoria-musical", "solfejo", "violino"],
    classroomVariant: "pink",
    email: "thiago.gomes@email.com",
    module: "Módulo II",
    moduleFilter: "module-ii",
    moduleVariant: "orange",
    name: "Thiago Gomes",
    phone: "(11) 96543-1111",
    status: "Inativo",
    statusFilter: "inactive",
  },
  {
    initials: "VS",
    classroom: "Classe 2",
    classroomFilter: "classe-2",
    classroomVariant: "blue",
    email: "vanessa.silva@email.com",
    module: "Módulo I",
    moduleFilter: "module-i",
    moduleVariant: "violet",
    name: "Vanessa Silva",
    phone: "(11) 96543-2222",
    status: "Ativo",
    statusFilter: "active",
  },
  {
    initials: "AF",
    classroom: "Classe 1",
    classroomFilter: "classe-1",
    classroomVariant: "pink",
    email: "amanda.ferraz@email.com",
    module: "Módulo I",
    moduleFilter: "module-i",
    moduleVariant: "violet",
    name: "Amanda Ferraz",
    phone: "(11) 96543-3333",
    status: "Ativo",
    statusFilter: "active",
  },
  {
    initials: "BC",
    classroom: "Classe 2",
    classroomFilter: "classe-2",
    classroomVariant: "blue",
    email: "beatriz.carmo@email.com",
    module: "Módulo I",
    moduleFilter: "module-i",
    moduleVariant: "violet",
    name: "Beatriz Carmo",
    phone: "(11) 96543-4444",
    status: "Inativo",
    statusFilter: "inactive",
  },
  {
    initials: "CD",
    classroom: "Classe 1",
    classroomFilter: "classe-1",
    classroomVariant: "pink",
    email: "caio.duarte@email.com",
    module: "Módulo I",
    moduleFilter: "module-i",
    moduleVariant: "violet",
    name: "Caio Duarte",
    phone: "(11) 96543-5555",
    status: "Ativo",
    statusFilter: "active",
  },
  {
    initials: "DE",
    classroom: "Classe 2",
    classroomFilter: "classe-2",
    classroomVariant: "blue",
    email: "daniela.esteves@email.com",
    module: "Módulo I",
    moduleFilter: "module-i",
    moduleVariant: "violet",
    name: "Daniela Esteves",
    phone: "(11) 96543-6666",
    status: "Trancamento",
    statusFilter: "locked",
  },
  {
    initials: "ER",
    classroom: "Classe 1",
    classroomFilter: "classe-1",
    classroomVariant: "pink",
    email: "eduardo.reis@email.com",
    module: "Módulo I",
    moduleFilter: "module-i",
    moduleVariant: "violet",
    name: "Eduardo Reis",
    phone: "(11) 96543-7777",
    status: "Ativo",
    statusFilter: "active",
  },
  {
    initials: "FL",
    classroom: "Classe 2",
    classroomFilter: "classe-2",
    classroomVariant: "blue",
    email: "fernanda.lopes@email.com",
    module: "Módulo I",
    moduleFilter: "module-i",
    moduleVariant: "violet",
    name: "Fernanda Lopes",
    phone: "(11) 96543-8888",
    status: "Inativo",
    statusFilter: "inactive",
  },
  {
    initials: "GV",
    classroom: "Classe 1",
    classroomFilter: "classe-1",
    classroomVariant: "pink",
    email: "gustavo.vieira@email.com",
    module: "Módulo I",
    moduleFilter: "module-i",
    moduleVariant: "violet",
    name: "Gustavo Vieira",
    phone: "(11) 95432-1111",
    status: "Ativo",
    statusFilter: "active",
  },
  {
    initials: "HL",
    classroom: "Classe 2",
    classroomFilter: "classe-2",
    classroomVariant: "blue",
    email: "heloisa.lacerda@email.com",
    module: "Módulo I",
    moduleFilter: "module-i",
    moduleVariant: "violet",
    name: "Heloísa Lacerda",
    phone: "(11) 95432-2222",
    status: "Ativo",
    statusFilter: "active",
  },
  {
    initials: "IR",
    classroom: "Classe 1",
    classroomFilter: "classe-1",
    classroomVariant: "pink",
    email: "igor.rangel@email.com",
    module: "Módulo I",
    moduleFilter: "module-i",
    moduleVariant: "violet",
    name: "Igor Rangel",
    phone: "(11) 95432-3333",
    status: "Trancamento",
    statusFilter: "locked",
  },
  {
    initials: "JL",
    classroom: "Classe 2",
    classroomFilter: "classe-2",
    classroomVariant: "blue",
    email: "juliana.leal@email.com",
    module: "Módulo I",
    moduleFilter: "module-i",
    moduleVariant: "violet",
    name: "Juliana Leal",
    phone: "(11) 95432-4444",
    status: "Ativo",
    statusFilter: "active",
  },
];
