import type { StudentRow } from "../_types/students.types";

export const STUDENT_ROWS: StudentRow[] = [
  {
    initials: "AC",
    classroom: "Teoria musical",
    classroomFilter: "teoria-musical",
    classroomVariant: "blue",
    email: "ana.costa@email.com",
    module: "Módulo I",
    moduleFilter: "module-i",
    moduleVariant: "violet",
    name: "Ana Clara Costa",
    phone: "(11) 98765-1111",
    status: "Ativo",
    statusFilter: "active",
  },
  {
    initials: "BH",
    classroom: "Violino",
    classroomFilter: "violino",
    classroomVariant: "pink",
    email: "bruno.silva@email.com",
    module: "Módulo II",
    moduleFilter: "module-ii",
    moduleVariant: "orange",
    name: "Bruno Henrique Silva",
    phone: "(11) 98765-2222",
    status: "Inativo",
    statusFilter: "inactive",
  },
  {
    initials: "CR",
    classroom: "Trompete",
    classroomFilter: "trompete",
    classroomVariant: "blue",
    email: "camila.rocha@email.com",
    module: "Módulo III",
    moduleFilter: "module-iii",
    moduleVariant: "orange",
    name: "Camila Rocha",
    phone: "(11) 98765-3333",
    status: "Trancamento",
    statusFilter: "locked",
  },
  {
    initials: "DP",
    classroom: "Teclado",
    classroomFilter: "teclado",
    classroomVariant: "pink",
    email: "diego.pires@email.com",
    module: "Módulo II",
    moduleFilter: "module-ii",
    moduleVariant: "orange",
    name: "Diego Pires",
    phone: "(11) 98765-4444",
    status: "Ativo",
    statusFilter: "active",
  },
  {
    initials: "ES",
    classroom: "Contrabaixo",
    classroomFilter: "contrabaixo",
    classroomVariant: "blue",
    email: "ester.sousa@email.com",
    module: "Módulo I",
    moduleFilter: "module-i",
    moduleVariant: "violet",
    name: "Ester Sousa",
    phone: "(11) 98765-5555",
    status: "Ativo",
    statusFilter: "active",
  },
];
