import type { StudentDetails } from "../_types/student-details.types";

export const STUDENT_DETAILS_BY_EMAIL_MOCK: Record<string, StudentDetails> = {
  "ana.costa@email.com": {
    address: {
      city: "São Paulo",
      complement: "Apto 42",
      neighborhood: "Vila Mariana",
      number: "120",
      state: "SP",
      street: "Rua das Flores",
      zipCode: "04101-100",
    },
    attendance: {
      history: [
        { date: "2026-05-11", notes: "Chegou no horário", status: "Presente" },
        { date: "2026-05-08", status: "Ausente" },
      ],
      justifiedAbsences: 1,
      presentRate: "92%",
      totalAbsences: 2,
      totalClasses: 24,
    },
    attachments: ["RG frente", "RG verso", "Comprovante de residência"],
    personalData: {
      birthDate: "2008-03-12",
      cpf: "123.456.789-00",
      fatherName: "Carlos Eduardo Costa",
      fullName: "Ana Clara Costa",
      maritalStatus: "Solteira",
      motherName: "Fernanda Lima Costa",
      nationality: "Brasileira",
      rg: "45.678.901-2",
      sex: "Feminino",
    },
    schoolEmail: "ana.costa@escola-musica.edu.br",
  },
  "bruno.silva@email.com": {
    address: {
      city: "São Paulo",
      complement: "Casa 2",
      neighborhood: "Ipiranga",
      number: "42",
      state: "SP",
      street: "Rua Maestro Lima",
      zipCode: "04210-050",
    },
    attendance: {
      history: [{ date: "2026-05-10", notes: "Participação ativa", status: "Presente" }],
      justifiedAbsences: 0,
      presentRate: "88%",
      totalAbsences: 3,
      totalClasses: 25,
    },
    attachments: ["RG frente", "RG verso"],
    personalData: {
      birthDate: "2007-11-02",
      cpf: "234.567.890-11",
      fatherName: "Marcos Silva",
      fullName: "Bruno Henrique Silva",
      maritalStatus: "Solteiro",
      motherName: "Luciana Souza Silva",
      nationality: "Brasileiro",
      rg: "56.789.012-3",
      sex: "Masculino",
    },
    schoolEmail: "bruno.silva@escola-musica.edu.br",
  },
  "camila.rocha@email.com": {
    address: {
      city: "São Bernardo do Campo",
      complement: "Bloco B",
      neighborhood: "Centro",
      number: "300",
      state: "SP",
      street: "Av. Harmonia",
      zipCode: "09710-110",
    },
    attendance: {
      history: [
        { date: "2026-05-12", notes: "Atestado médico", status: "Justificado" },
        { date: "2026-05-09", status: "Ausente" },
      ],
      justifiedAbsences: 2,
      presentRate: "79%",
      totalAbsences: 5,
      totalClasses: 24,
    },
    attachments: ["RG frente", "RG verso", "CPF", "Laudo médico"],
    personalData: {
      birthDate: "2009-08-19",
      cpf: "345.678.901-22",
      fatherName: "Roberto Rocha",
      fullName: "Camila Rocha",
      maritalStatus: "Solteira",
      motherName: "Patrícia Almeida Rocha",
      nationality: "Brasileira",
      rg: "67.890.123-4",
      sex: "Feminino",
    },
    schoolEmail: "camila.rocha@escola-musica.edu.br",
  },
  "felipe.martins@email.com": {
    address: {
      city: "São Paulo",
      complement: "-",
      neighborhood: "Mooca",
      number: "88",
      state: "SP",
      street: "Rua Padre Raposo",
      zipCode: "03118-010",
    },
    attendance: {
      history: [{ date: "2026-05-13", notes: "Participou da aula prática", status: "Presente" }],
      justifiedAbsences: 0,
      presentRate: "95%",
      totalAbsences: 1,
      totalClasses: 20,
    },
    attachments: ["Foto 3x4", "RG", "Comprovante de residência"],
    personalData: {
      birthDate: "2008-01-21",
      cpf: "456.789.012-33",
      fatherName: "André Martins",
      fullName: "Felipe Martins",
      maritalStatus: "Solteiro",
      motherName: "Célia Martins",
      nationality: "Brasileiro",
      rg: "78.901.234-5",
      sex: "Masculino",
    },
    schoolEmail: "felipe.martins@escola-musica.edu.br",
  },
  "giovana.lima@email.com": {
    address: {
      city: "São Paulo",
      complement: "Casa",
      neighborhood: "Tatuapé",
      number: "510",
      state: "SP",
      street: "Rua Serra de Botucatu",
      zipCode: "03317-001",
    },
    attendance: {
      history: [{ date: "2026-05-09", notes: "Sem participação", status: "Ausente" }],
      justifiedAbsences: 0,
      presentRate: "72%",
      totalAbsences: 6,
      totalClasses: 22,
    },
    attachments: ["RG"],
    personalData: {
      birthDate: "2009-06-03",
      cpf: "567.890.123-44",
      fatherName: "Paulo Lima",
      fullName: "Giovana Lima",
      maritalStatus: "Solteira",
      motherName: "Lídia Lima",
      nationality: "Brasileira",
      rg: "89.012.345-6",
      sex: "Feminino",
    },
    schoolEmail: "giovana.lima@escola-musica.edu.br",
  },
  "henrique.santos@email.com": {
    address: {
      city: "Guarulhos",
      complement: "Apto 12",
      neighborhood: "Centro",
      number: "140",
      state: "SP",
      street: "Rua Sete de Setembro",
      zipCode: "07011-020",
    },
    attendance: {
      history: [{ date: "2026-05-14", notes: "Boa evolução", status: "Presente" }],
      justifiedAbsences: 1,
      presentRate: "90%",
      totalAbsences: 2,
      totalClasses: 20,
    },
    attachments: ["RG", "CNH"],
    personalData: {
      birthDate: "2007-10-11",
      cpf: "678.901.234-55",
      fatherName: "Marcos Santos",
      fullName: "Henrique Santos",
      maritalStatus: "Solteiro",
      motherName: "Diana Santos",
      nationality: "Brasileiro",
      rg: "90.123.456-7",
      sex: "Masculino",
    },
    schoolEmail: "henrique.santos@escola-musica.edu.br",
  },
  "isabela.melo@email.com": {
    address: {
      city: "Santo André",
      complement: "Bloco C",
      neighborhood: "Jardim",
      number: "312",
      state: "SP",
      street: "Rua das Monções",
      zipCode: "09090-521",
    },
    attendance: {
      history: [{ date: "2026-05-07", notes: "Atestado enviado", status: "Justificado" }],
      justifiedAbsences: 2,
      presentRate: "76%",
      totalAbsences: 5,
      totalClasses: 21,
    },
    attachments: ["RG", "Comprovante de residência"],
    personalData: {
      birthDate: "2008-12-29",
      cpf: "789.012.345-66",
      fatherName: "Rogério Melo",
      fullName: "Isabela Melo",
      maritalStatus: "Solteira",
      motherName: "Marta Melo",
      nationality: "Brasileira",
      rg: "11.234.567-8",
      sex: "Feminino",
    },
    schoolEmail: "isabela.melo@escola-musica.edu.br",
  },
  "joao.pedro@email.com": {
    address: {
      city: "São Paulo",
      complement: "-",
      neighborhood: "Penha",
      number: "76",
      state: "SP",
      street: "Rua Mirandinha",
      zipCode: "03694-010",
    },
    attendance: {
      history: [{ date: "2026-05-15", notes: "Participou do coral", status: "Presente" }],
      justifiedAbsences: 0,
      presentRate: "93%",
      totalAbsences: 1,
      totalClasses: 16,
    },
    attachments: ["Foto 3x4", "RG"],
    personalData: {
      birthDate: "2009-02-05",
      cpf: "890.123.456-77",
      fatherName: "Carlos Pedro",
      fullName: "João Pedro",
      maritalStatus: "Solteiro",
      motherName: "Neide Pedro",
      nationality: "Brasileiro",
      rg: "22.345.678-9",
      sex: "Masculino",
    },
    schoolEmail: "joao.pedro@escola-musica.edu.br",
  },
  "karina.silveira@email.com": {
    address: {
      city: "Osasco",
      complement: "Casa 2",
      neighborhood: "Bela Vista",
      number: "245",
      state: "SP",
      street: "Rua Cipriano Tavares",
      zipCode: "06083-020",
    },
    attendance: {
      history: [{ date: "2026-05-06", notes: "Sem justificativa", status: "Ausente" }],
      justifiedAbsences: 0,
      presentRate: "70%",
      totalAbsences: 7,
      totalClasses: 23,
    },
    attachments: ["RG", "CNH", "Comprovante de residência"],
    personalData: {
      birthDate: "2007-04-17",
      cpf: "901.234.567-88",
      fatherName: "João Silveira",
      fullName: "Karina Silveira",
      maritalStatus: "Solteira",
      motherName: "Sandra Silveira",
      nationality: "Brasileira",
      rg: "33.456.789-0",
      sex: "Feminino",
    },
    schoolEmail: "karina.silveira@escola-musica.edu.br",
  },
  "lucas.ribeiro@email.com": {
    address: {
      city: "São Caetano do Sul",
      complement: "Apto 31",
      neighborhood: "Santa Paula",
      number: "980",
      state: "SP",
      street: "Rua Piauí",
      zipCode: "09541-150",
    },
    attendance: {
      history: [{ date: "2026-05-16", notes: "Evoluiu no repertório", status: "Presente" }],
      justifiedAbsences: 1,
      presentRate: "89%",
      totalAbsences: 3,
      totalClasses: 22,
    },
    attachments: ["RG", "Foto 3x4"],
    personalData: {
      birthDate: "2008-09-14",
      cpf: "012.345.678-99",
      fatherName: "Fábio Ribeiro",
      fullName: "Lucas Ribeiro",
      maritalStatus: "Solteiro",
      motherName: "Elaine Ribeiro",
      nationality: "Brasileiro",
      rg: "44.567.890-1",
      sex: "Masculino",
    },
    schoolEmail: "lucas.ribeiro@escola-musica.edu.br",
  },
  "mariana.teixeira@email.com": {
    address: {
      city: "Diadema",
      complement: "Fundos",
      neighborhood: "Centro",
      number: "67",
      state: "SP",
      street: "Rua Manoel da Nóbrega",
      zipCode: "09910-120",
    },
    attendance: {
      history: [{ date: "2026-05-04", notes: "Trancamento solicitado", status: "Justificado" }],
      justifiedAbsences: 3,
      presentRate: "68%",
      totalAbsences: 8,
      totalClasses: 25,
    },
    attachments: ["RG", "Comprovante de residência", "Declaração"],
    personalData: {
      birthDate: "2007-07-30",
      cpf: "123.456.789-10",
      fatherName: "Rafael Teixeira",
      fullName: "Mariana Teixeira",
      maritalStatus: "Solteira",
      motherName: "Cris Teixeira",
      nationality: "Brasileira",
      rg: "55.678.901-2",
      sex: "Feminino",
    },
    schoolEmail: "mariana.teixeira@escola-musica.edu.br",
  },
};
