import type { StudentDetails } from "../_types/student-details.types";

export const STUDENT_DETAILS_BY_EMAIL_MOCK: Record<string, StudentDetails> = {
  "ana.costa@email.com": {
    address: {
      city: "São Paulo",
      complement: "Apto 42",
      neighborhood: "Vila Mariana",
      number: "120",
      state: "SP",
      street: "Rua das Flores",
      zipCode: "04101-100",
    },
    attendance: {
      history: [
        { date: "2026-05-11", notes: "Chegou no horário", status: "Presente" },
        { date: "2026-05-08", status: "Ausente" },
      ],
      justifiedAbsences: 1,
      presentRate: "92%",
      totalAbsences: 2,
      totalClasses: 24,
    },
    attachments: ["RG frente", "RG verso", "Comprovante de residência"],
    personalData: {
      birthDate: "2008-03-12",
      cpf: "123.456.789-00",
      fatherName: "Carlos Eduardo Costa",
      fullName: "Ana Clara Costa",
      maritalStatus: "Solteira",
      motherName: "Fernanda Lima Costa",
      nationality: "Brasileira",
      rg: "45.678.901-2",
      sex: "Feminino",
    },
    schoolEmail: "ana.costa@escola-musica.edu.br",
  },
  "bruno.silva@email.com": {
    address: {
      city: "São Paulo",
      complement: "Casa 2",
      neighborhood: "Ipiranga",
      number: "42",
      state: "SP",
      street: "Rua Maestro Lima",
      zipCode: "04210-050",
    },
    attendance: {
      history: [{ date: "2026-05-10", notes: "Participação ativa", status: "Presente" }],
      justifiedAbsences: 0,
      presentRate: "88%",
      totalAbsences: 3,
      totalClasses: 25,
    },
    attachments: ["RG frente", "RG verso"],
    personalData: {
      birthDate: "2007-11-02",
      cpf: "234.567.890-11",
      fatherName: "Marcos Silva",
      fullName: "Bruno Henrique Silva",
      maritalStatus: "Solteiro",
      motherName: "Luciana Souza Silva",
      nationality: "Brasileiro",
      rg: "56.789.012-3",
      sex: "Masculino",
    },
    schoolEmail: "bruno.silva@escola-musica.edu.br",
  },
  "camila.rocha@email.com": {
    address: {
      city: "São Bernardo do Campo",
      complement: "Bloco B",
      neighborhood: "Centro",
      number: "300",
      state: "SP",
      street: "Av. Harmonia",
      zipCode: "09710-110",
    },
    attendance: {
      history: [
        { date: "2026-05-12", notes: "Atestado médico", status: "Justificado" },
        { date: "2026-05-09", status: "Ausente" },
      ],
      justifiedAbsences: 2,
      presentRate: "79%",
      totalAbsences: 5,
      totalClasses: 24,
    },
    attachments: ["RG frente", "RG verso", "CPF", "Laudo médico"],
    personalData: {
      birthDate: "2009-08-19",
      cpf: "345.678.901-22",
      fatherName: "Roberto Rocha",
      fullName: "Camila Rocha",
      maritalStatus: "Solteira",
      motherName: "Patrícia Almeida Rocha",
      nationality: "Brasileira",
      rg: "67.890.123-4",
      sex: "Feminino",
    },
    schoolEmail: "camila.rocha@escola-musica.edu.br",
  },
};

